---
title: "p8105_hw5_xt2288"
author: "Xiaoting Tang"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
library(tidyverse)
set.seed(1)
```

# Problem 1


# Problem 2

```{r message=FALSE}
long_study = 
  data.frame(file_name = list.files("data/problem2data", full.names = TRUE)) |>
  mutate(obs = purrr::map(file_name, read_csv)) |>
  mutate(arm = list.files("data/problem2data"),
         subject_id = list.files("data/problem2data")) |>
  mutate(subject_id = gsub("\\D", "",  subject_id),
         arm = substr(arm, 1, 3),
         arm = 
           case_match(
             arm,
             "con" ~ "control",
             "exp" ~ "experimental"
           )) |>
  unnest(cols = c(obs)) |>
  relocate(arm, subject_id, everything()) |>
  select(-file_name) |>
  pivot_longer(
    week_1:week_8,
    names_to = "week", 
    values_to = "data"
  )

long_study |>
  ggplot(aes(x = week, y = data, group = subject_id, color = subject_id)) + 
  geom_line() +
  facet_grid(~arm)
```

The values of the subjects in the experimental group increase from week 1 to week 8. The values for the control group does not change much.


# Problem 3

```{r}
n = 30
sigma = 5
mu = 0
alpha = 0.05

set.seed(1)


sim_mean = function(n, mu = mu, sigma = sigma) {
  sim_data = tibble(rnorm(n, mean = mu, sd = 5))
  
  result = t.test(sim_data, mu = 0, conf.level = 0.95)
  
  result |>
    broom::tidy() |>
    select(estimate, p.value)
}


output = vector("list", 5000)

for (i in 1:5000) {
  
  output[[i]] = sim_mean(n, 0, sigma)
}

sim_results_0 = bind_rows(output)
```

```{r}
output = vector("list", 5000)
for (i in 1:5000) {output[[i]] = sim_mean(n, 1, sigma)}
sim_results_1 = bind_rows(output)
```

```{r}
output = vector("list", 5000)
for (i in 1:5000) {output[[i]] = sim_mean(n, 2, sigma)}
sim_results_2 = bind_rows(output)
```

```{r}
output = vector("list", 5000)
for (i in 1:5000) {output[[i]] = sim_mean(n, 3, sigma)}
sim_results_3 = bind_rows(output)
```

```{r}
output = vector("list", 5000)
for (i in 1:5000) {output[[i]] = sim_mean(n, 4, sigma)}
sim_results_4 = bind_rows(output)
```

```{r}
output = vector("list", 5000)
for (i in 1:5000) {output[[i]] = sim_mean(n, 5, sigma)}
sim_results_5 = bind_rows(output)
```

```{r}
output = vector("list", 5000)
for (i in 1:5000) {output[[i]] = sim_mean(n, 6, sigma)}
sim_results_6 = bind_rows(output)
```

```{r}
power_0 = sum(sim_results_0$p.value < 0.05)/5000
power_1 = sum(sim_results_1$p.value < 0.05)/5000
power_2 = sum(sim_results_2$p.value < 0.05)/5000
power_3 = sum(sim_results_3$p.value < 0.05)/5000
power_4 = sum(sim_results_4$p.value < 0.05)/5000
power_5 = sum(sim_results_5$p.value < 0.05)/5000
power_6 = sum(sim_results_6$p.value < 0.05)/5000

effect_size_power = 
  data.frame(power = c(power_0,power_1,power_2,power_3,power_4,power_5,power_6),
             effect_size = c(0,1,2,3,4,5,6))

effect_size_power |>
  ggplot(aes(x = effect_size, y = power)) +
  geom_point() +
  geom_line() +
  labs(title = "Power vs. Effect Size",
       x = "Effect Size",
       y = "Power")
```

As the effective size increases, the power increases.
